title: warmcolors
description: >- # this means to ignore newlines until "baseurl:"
  warmcolors
baseurl: "/warmcolors"
url: "https://lowply.net"
markdown: kramdown
exclude:
  - script
  - README.md
  - Makefile
