title: warmcolors.info
email: lowply@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  warmcolors.info
baseurl: ""
url: ""
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
