title: warmcolors
description: >- # this means to ignore newlines until "baseurl:"
  warmcolors
baseurl: ""
url: "https://lowply.net/warmcolors"
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
