name: Build and Deploy
on:
  push:
    branches: main
  workflow_dispatch:
permissions:
  id-token: write
  contents: read
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true
      - name: Build Jekyll
        run: bundle exec jekyll build
      - name: "Login to Azure with OIDC"
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to S3
        run: ./script/deploy.sh
