name: Build and Deploy
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          bundler-cache: true
      - name: Build Jekyll
        run: bundle exec jekyll build
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/oidc/GitHubActions@warmcolors.info
          aws-region: ap-northeast-1
      - name: Deploy to S3
        run: ./script/deploy.sh
